version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    image: backend:v1
    restart: always
    build:
      context: backend/.
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: example
      DB_NAME: test
    depends_on:
      - mongo
    ports:
      - 18888:18888

  frontend:
    image: frontend:v1
    restart: always
    build:
      context: frontend/.
    environment:
      API_HOST: backend
      API_PORT: 18888
    ports:
      - 80:80
    depends_on:
      - backend
